# Generated by Django 5.2.9 on 2025-12-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='UTC date and time of the record')),
                ('country_code', models.CharField(help_text='ISO Country Code (e.g., GB, FR, DE)', max_length=5)),
                ('resource_type', models.CharField(help_text='Energy source (e.g., Wind, Solar, Nuclear, Fossil Gas)', max_length=50)),
                ('actual_generation_mw', models.FloatField(blank=True, help_text='Real-time energy generation in MW', null=True)),
                ('forecast_generation_mw', models.FloatField(blank=True, help_text='Day-ahead forecasted generation in MW', null=True)),
            ],
            options={
                'verbose_name_plural': 'Energy Generation Records',
                'indexes': [models.Index(fields=['timestamp', 'country_code'], name='api_energyg_timesta_9cb64e_idx')],
            },
        ),
    ]
