# Generated by Django 5.2.9 on 2025-12-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='energygeneration',
            name='api_energyg_timesta_9cb64e_idx',
        ),
        migrations.AlterField(
            model_name='energygeneration',
            name='actual_generation_mw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energygeneration',
            name='country_code',
            field=models.CharField(help_text='ISO Country Code (e.g., GB)', max_length=50),
        ),
        migrations.AlterField(
            model_name='energygeneration',
            name='forecast_generation_mw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='energygeneration',
            name='resource_type',
            field=models.CharField(help_text='Energy source (e.g., Wind)', max_length=100),
        ),
    ]
